### ISSUE TITLE
PLD/TI not adjusted by slice timing for 2D datasets?

### ISSUE THREAD

**Issue by conan-chen94** [PennLINC/aslprep#189]
I have a 2D PCASL dataset processed through ASLPrep. However, it looks like the slice-timing information is used to run AFNI's 3dTshift on the raw tag/control data, but not to adjust the PLDs/TIs for individual slices before performing CBF quantification. Is this reading of the current behavior correct?

On the same dataset, I observed lower CBF values from ASLprep compared to an in-house MATLAB script for quantifying CBF which accounted for slice-delay in the PLD values. On the other hand, when adjusting the MATLAB script to ignore slice-delay (i.e. use the PLD of the very first slice, for all slices), the CBF values were much more similar to ASLprep. ASLprep ran through to completion, and the report also indicated slice-timing correction was performed.

If this is the current behavior, it would be great to use the slice-delay in PLD/TI in CBF quantification per the white paper recommendation. 

If it is already supposed to be in there, then I'd appreciate any pointers on running it properly :)

EDIT: This was back when I was using 0.2.7. I have not had a chance to re-test with 0.2.8.

**Comment by tsalo** [comment]
@conan-chen94 sorry for the delay. I've only recently started maintaining ASLPrep, but I can start looking at this now. Can you explain how your in-house MATLAB script accounts for slice delay? Does it just shift the PLDs/TIs based on which slice the correction uses?

AFAIK, slice timing is not accounted for in the PLDs/TIs, but it sounds like a good idea.

**Comment by tsalo** [comment]
Since CBF calculation happens after motion correction and distortion correction, the original slice-wise PLD shifts won't necessarily be accurate by the time we start calculating CBF. In a sense, each voxel in each volume of the motion-corrected ASL file would reflect a mix of PLDs. I'm thinking of creating a NIFTI file with the shifted PLDs for each slice, and then run that through the motion correction and distortion correction steps, so that the offsets are averaged as necessary. I will then average the altered, voxel- and volume-wise PLDs over time for simplicity's sake when calculating CBF.
