### ISSUE TITLE
aslprep: error: Path does not exist

### ISSUE THREAD

**Issue by emmalxw** [PennLINC/aslprep#190]
I try to run aslprep, but it always shows 'aslprep: error: Path does not exist</fs02/oe24/Emma/Projects/data_mc/data_bids/>', but it actually exist. 
<img width="815" alt="Screen Shot 2022-07-26 at 6 07 08 pm" src="https://user-images.githubusercontent.com/90241412/180956277-dab7824f-ff68-4fa4-a874-577b2a879467.png">

Does anyone what might cause the issue? I guess it's a tiny problem, but I cannot figure it out.
Thanks in advance!

**Comment by cookpa** [comment]
Are you running in a container? You need to mount the paths with `-v` for docker or `-B` for singularity. The example from the docs is

```
$ docker run -ti --rm \
    -v $HOME/fullds005:/data:ro \
    -v $HOME/dockerout:/out \
    -v $HOME/.licenses/freesurfer/license.txt:/opt/freesurfer/license.txt \
    pennlinc/aslprep:latest \
    /data /out/out \
    participant \
    --ignore fieldmaps
```

Here the path `$HOME/fullds005` on the local computer is mounted to `/data` in the container. When we pass args to aslprep, we use the container path `/data`.

So you would want something like `-v /fs02/oe24/Emma/Projects/data_mc/data_bids:/data`

**Comment by emmalxw** [comment]
Hi cookpa,
Thank you so much for the reply. I think we use singularity. (https://docs.massive.org.au/M3/software/software.html) I forgot we had used -v for another similar software before. But it still doesn't work after I try -v or -B. Can you have a look again my screenshot below? Thanks!
<img width="989" alt="Screen Shot 2022-07-27 at 6 03 15 pm" src="https://user-images.githubusercontent.com/90241412/181199243-1a529b97-d2c2-476d-a163-815873dc5eba.png">

**Comment by emmalxw** [comment]
By the way, it worked in last year when my first trial, but alerted some parameters were not right. I use BASIL to process the data, they look alright.

**Comment by cookpa** [comment]
It looks like you're loading aslprep from a module and calling the aslprep directly. If it's not containerized, you shouldn't need to use -B to mount things.

I have never run the software outside of Singularity. Maybe whoever made the module could assist?

**Comment by caugolm** [comment]
It looks like the way you're set up is with aslprep installed as a module. (-v used as a flag inside the aslprep command as you have it turns on verbose mode.). I haven't used aslprep as a module so I don't know if path binding is in any way weird or affected by that, but just to make sure it isn't something silly I'd try using both absolute and relative paths to define the bids and output directories. I might also try appending ${bids_dir} to the PATH variable:
`export PATH=${PATH}:${bids_dir}"`
Sort of secondarily I might suggest updating to a more recent version of ASLPrep, as there have been a number of significant changes since 0.2.7. From the link you shared, it looks like your system/admin supports singularity installations, and the ASLPrep authors encourage this type of install.

edited for formatting
