### ISSUE TITLE
Incorrectly labeled GM WM CSF masks

### ISSUE THREAD

**Issue by josephmje** [PennLINC/aslprep#191]
After running aslprep v0.2.7 with the `--anat-derivatives` flag (using previously pre-processed anatomical outputs from fmriprep), we noticed that we were getting similar values in the `quality_control_cbf.csv` for `GMmeanCBF` and `WMmeanCBF`. 

We looked through the work directory and noticed that there's a mismatch between the folder names in `compt_qccbf_wf` and the files within:

csf_tfm -> label-WM_probseg_trans
gm_tfm -> label-CSF_probseg_trans
wm_wfm -> label-GM_probseg_trans

Could this be causing our issue?

**Comment by caugolm** [comment]
I haven't run ASLPrep with the --anat-derivatives flag, but I know v0.2.8 included a number of important bug fixes so updating the version might be worth trying. 
Aside from that, do the Gm_wm_ratio values reflect the GMmeanCBF and WMmeanCBF values? Do the segmentations look reasonable in the ASL space? Also, though the (relatively) commonly accepted estimate is that WM CBF is about 40% of the GM CBF value, when looking at "whole tissue" means like this the values are often closer together because of partial volume effects.

**Comment by josephmje** [comment]
Thanks for the suggestions @caugolm! We tried v0.2.8 and still see the same issue. Running aslprep **without** the `--anat-derivatives` flag (using FSL FAST) did seem to give us more reasonable results.

To clarify, below is a screenshot of what happens when running with the `--anat-derivatives` flag:
![image](https://user-images.githubusercontent.com/22102194/184181760-70148edf-d96b-4233-a61d-643a17c04826.png)

It looks like the wrong inputs are being passed into the `cbf_compt_wf` workflow.
