### ISSUE TITLE
ASLprep with CBF maps (GE)

### ISSUE THREAD

**Issue by frdarya** [PennLINC/aslprep#197]
Unable to run aslprep with a CBF map computed from a GE scanner:
The aslcontext.tsv includes only cbf as volume (following the BIDS formatting), but get an error that there is a mismatch between the tsv file and the number of volumes in the niftii header:
dim1		        128
dim2		128
dim3		30
dim4		1

**Comment by frdarya** [comment]
any update on this?

**Comment by caugolm** [comment]
My guess is that the issue is related to it expecting a "one volume" image to be three dimensions, instead of 4. @tsalo might be interested in debugging this, but to get around similar issues elsewhere I've done hacky things to 4D images with only one time dimension to convert them to 3D, for example, using something like TimeSeriesDisassemble in ANTs, or if you prefer fsl, something like fslmeants.

**Comment by tsalo** [comment]
Thank you @caugolm, I will take a look.

@frdarya can you post the full traceback from the error?

**Comment by frdarya** [comment]
Sure, here's the error:
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
bids-validator@1.8.4

	1: [ERR] The number of volumes in the '*_aslcontext.tsv' for this file does not match the number of values in the NIfTI header. (code: 165 - ASLCONTEXT_TSV_NOT_CONSISTENT)
		./sub-0005/perf/sub-0005_asl.nii

**Comment by tsalo** [comment]
Ah, so it's a BIDS validator error. I assumed it was an internal issue with ASLPrep. Can you share the contents of your aslcontext file?

One other useful step might be to try validating your dataset using the most recent version of the validator (https://bids-standard.github.io/bids-validator/). If this is a bug on the validator's part, it would be good to know if the bug is still present. If it is a bug, but the newest version of the validator doesn't have it, then I can update the version used by ASLPrep.

**Comment by frdarya** [comment]
The aslcotext file is just two rows following the ASL BIDS format:
volume_type
cbf

I tried to validate the dataset using the link you've sent, but I still get the same error:

Error 2: [Code 165] ASLCONTEXT_TSV_NOT_CONSISTENT
The number of volumes in the '*_aslcontext.tsv' for this file does not match the number of values in the NIfTI header.

**Comment by tsalo** [comment]
In that case, I think it must be a problem with the validator. There's a related NeuroStars topic: https://neurostars.org/t/ge-asl-the-number-of-volumes-in-the-aslcontext-tsv-for-this-file-does-not-match-the-number-of-values-in-the-nifti-header-code-165-aslcontext-tsv-not-consistent/22446, but the problem was never resolved. Perhaps you can follow up there, or open an issue in the bids-validator repository?

**Comment by tsalo** [comment]
@frdarya have you had a chance to follow up with the validator team?
